root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/golem-server ./cmd/server && go build -o ./tmp/golem ./cmd/golem"
  bin = "./tmp/golem-server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
